import React from 'react';

const TermsAndConditions = () => {
  return (
    <div style={styles.container}>
      <h1 style={styles.heading}>End User Agreement</h1>
      <p>
        This End User Agreement (the “Agreement”) is made between you (the “User” or “You”) and Raj Khosla &amp; Co Pvt Ltd, a private limited company having its registered office at 812, Surya Kiran building, 19 KG Marg, New Delhi 110001 (“RKPL &amp; its sister concerns (RKPL GROUP)”, “Us” or “We”, which term shall include its successors and permitted assigns). The User and RKPL GROUP shall be collectively referred to as the “Parties” and individually as a “Party”.
      </p>

      <p>
        You hereby consent to RKPL GROUP being appointed as your authorised representative to receive your Credit Information from Experian for the purpose of providing access to credit and targeted offers pursuant to the Individual Consumer Consent (“End Use Purpose”).
      </p>

      <p>
        BY EXECUTING THIS AGREEMENT / CONSENT FORM, YOU ARE EXPRESSLY AGREEING TO ACCESS THE EXPERIAN CREDIT INFORMATION REPORT AND CREDIT SCORE, AGGREGATE SCORES, INFERENCES, REFERENCES AND DETAILS (AS DEFINED BELOW)(TOGETHER REFERRED AS “CREDIT INFORMATION”). YOU HEREBY ALSO IRREVOCABLY AND UNCONDITIONALLY CONSENT TO SUCH CREDIT INFORMATION BEING PROVIDED BY EXPERIAN TO YOU AND RKPL GROUP BY USING EXPERIAN TOOLS, ALGORITHMS AND DEVICES AND YOU HEREBY AGREE, ACKNOWLEDGE AND ACCEPT THE TERMS AND CONDITIONS SET FORTH HEREIN.
      </p>

      <h2 style={styles.subHeading}>Terms and Conditions:</h2>
      <ol>
        <li>
          <strong>Information Collection, Use, Confidentiality, No-Disclosure and Data Purging</strong>
          <p>
            MyMoneyMantra shall access your Credit Information as your authorized representative and MyMoneyMantra shall use the Credit Information for limited End Use Purpose consisting of and in relation to the services proposed to be availed by you from MyMoneyMantra. We shall not aggregate, retain, store, copy, reproduce, republish, upload, post, transmit, sell or rent the Credit Information to any other person and the same cannot be copied or reproduced other than as agreed herein and in furtherance to CICRA.
          </p>
          <p>
            The Parties agree to protect and keep confidential the Credit Information both online and offline.
          </p>
          <p>
            The Credit Information shared by you, or received on by us on your behalf shall be destroyed, purged, erased promptly within 1 (one) Business Day of upon the completion of the transaction/ End Use Purpose for which the Credit Information report was procured.
          </p>
        </li>
        <li>
          <strong>Governing Law and Jurisdiction</strong>
          <p>
            The relationship between you and MyMoneyMantra shall be governed by laws of India and all claims or disputes arising therefrom shall be subject to the exclusive jurisdiction of the courts of Mumbai.
          </p>
        </li>
      </ol>

      <h2 style={styles.subHeading}>Definitions:</h2>
      <ul>
        <li>
          <strong>Business Day:</strong> means a day (other than a public holiday) on which banks are open for general business in Mumbai.
        </li>
        <li>
          <strong>Credit Information Report:</strong> means the credit information / scores / aggregates / variables / inferences or reports which shall be generated by Experian.
        </li>
        <li>
          <strong>Credit Score:</strong> means the score which shall be mentioned on the Credit Information Report which shall be computed by Experian.
        </li>
        <li>
          <strong>CICRA:</strong> shall mean the Credit Information Companies (Regulation) Act, 2005 read with the Credit Information Companies Rules, 2006 and the Credit Information Companies Regulations, 2006, and shall include any other rules and regulations prescribed thereunder.
        </li>
      </ul>

      <p>
        PLEASE READ THE ABOVEMENTIONED TERMS AND CONDITIONS AND CLICK ON “ACCEPT” FOLLOWED BY THE LINK BELOW TO COMPLETE THE AUTHORISATION PROCESS/ FOR SHARING OF YOUR CREDIT INFORMATION BY EXPERIAN WITH MyMoneyMantra IN ITS CAPACITY AS YOUR AUTHORISED REPRESENTATIVE.
      </p>

      <p>
        ** This document is an electronic record in terms of the Information Technology Act, 2000 and Rules made thereunder, and the amended provisions pertaining to electronic records.
      </p>
    </div>
  );
};

const styles = {
  container: {
    padding: '20px',
  },
  heading: {
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
  subHeading: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginBottom: '10px',
  },
};

export default TermsAndConditions;
